### ISSUE TITLE
Missing some monitor item?

### ISSUE THREAD

**Issue by navyaijm2017** [apache/rocketmq-exporter#10]
**Describe the bug**
有部分topic的rocketmq_producer_tps这个指标没有采集，如何解决这个问题呢
![image](https://user-images.githubusercontent.com/29217326/70955689-b288e080-20ac-11ea-82e6-6062dd5527b1.png)
![image](https://user-images.githubusercontent.com/29217326/70955826-1c08ef00-20ad-11ea-8323-1d873932d263.png)
![image](https://user-images.githubusercontent.com/29217326/70955835-232ffd00-20ad-11ea-9dba-ce1316fc0a69.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by navyaijm2017** [comment]
yes

**Comment by francisoliverlee** [comment]
@navyaijm2017 try this, https://github.com/apache/rocketmq-exporter/pull/9
it collect all metrics

**Comment by navyaijm2017** [comment]
Is this project no longer maintained? Chance to merge this fix to master？

**Comment by francisoliverlee** [comment]
> Is this project no longer maintained? Chance to merge this fix to master？

the project will be maintained always.
need to test fully, you can just use it before finishing merge

**Comment by francisoliverlee** [comment]
@navyaijm2017 any problem, leave a msg here at me
