### ISSUE TITLE
can't find rocketmq-exporter in hub.docker.com?

### ISSUE THREAD

**Issue by Yelijah** [apache/rocketmq-exporter#104]
can't find apache offical rocketmq-exporter in hub.docker.com? it seems that I have to build image by myself?

**Comment by celery-xqq** [comment]
bro , I have the same problem

**Comment by waney316** [comment]
you can clone this project and build to docker image

**Comment by francisoliverlee** [comment]
@celery-xqq  an example for your consideration
https://github.com/rocketmq-ps/rocketmq-exporter-docker

**Comment by drivebyer** [comment]
readme should be fixed.
