### ISSUE TITLE
 After rocketmq broker version changed to  4.5.1 , mvn clean install failed and how to resove it?

### ISSUE THREAD

**Issue by ljzlegendice** [apache/rocketmq-exporter#106]
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /mnt/d/soft/maven38
Java version: 1.8.0_312, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en, platform encoding: UTF-8

broker version 4.8.0 compile is normal,but  broker version changed to 4.5.1   compile failed
I want to monitor the RocketMQ Version 4.5.1
pom.xml:
<rocketmq.version>4.5.1</rocketmq.version>
application.yml
rocketmqVersion: 4_5_1

[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /mnt/e/rocketmq_export/rocketmq-exporter-master/src/main/java/org/apache/rocketmq/exporter/service/client/MQAdminExtImpl.java:[27,34] cannot find symbol
  symbol:   class AclConfig
  location: package org.apache.rocketmq.common
[ERROR] /mnt/e/rocketmq_export/rocketmq-exporter-master/src/main/java/org/apache/rocketmq/exporter/service/client/MQAdminExtImpl.java:[28,34] cannot find symbol
  symbol:   class PlainAccessConfig
  location: package org.apache.rocketmq.common
[ERROR] /mnt/e/rocketmq_export/rocketmq-exporter-master/src/main/java/org/apache/rocketmq/exporter/service/client/MQAdminExtImpl.java:[39,48] cannot find symbol
  symbol:   class ClusterAclVersionInfo
  location: package org.apache.rocketmq.common.protocol.body
[ERROR] /mnt/e/rocketmq_export/rocketmq-exporter-master/src/main/java/org/apache/rocketmq/exporter/service/client/MQAdminExtImpl.java:[120,9] cannot find symbol
  symbol:   class PlainAccessConfig
  location: class org.apache.rocketmq.exporter.service.client.MQAdminExtImpl
[ERROR] /mnt/e/rocketmq_export/rocketmq-exporter-master/src/main/java/org/apache/rocketmq/exporter/service/client/MQAdminExtImpl.java:[134,22] cannot find symbol
  symbol:   class ClusterAclVersionInfo
  location: class org.apache.rocketmq.exporter.service.client.MQAdminExtImpl
[ERROR] /mnt/e/rocketmq_export/rocketmq-exporter-master/src/main/java/org/apache/rocketmq/exporter/service/client/MQAdminExtImpl.java:[140,22] cannot find symbol
  symbol:   class AclConfig
  location: class org.apache.rocketmq.exporter.service.client.MQAdminExtImpl
[ERROR] /mnt/e/rocketmq_export/rocketmq-exporter-master/src/main/java/org/apache/rocketmq/exporter/service/client/MQAdminExtImpl.java:[119,5] method does not override or implement a method from a supertype
[ERROR] /mnt/e/rocketmq_export/rocketmq-exporter-master/src/main/java/org/apache/rocketmq/exporter/service/client/MQAdminExtImpl.java:[124,5] method does not override or implement a method from a supertype
[ERROR] /mnt/e/rocketmq_export/rocketmq-exporter-master/src/main/java/org/apache/rocketmq/exporter/service/client/MQAdminExtImpl.java:[129,5] method does not override or implement a method from a supertype
[ERROR] /mnt/e/rocketmq_export/rocketmq-exporter-master/src/main/java/org/apache/rocketmq/exporter/service/client/MQAdminExtImpl.java:[134,5] method does not override or implement a method from a supertype
[ERROR] /mnt/e/rocketmq_export/rocketmq-exporter-master/src/main/java/org/apache/rocketmq/exporter/service/client/MQAdminExtImpl.java:[140,5] method does not override or implement a method from a supertype
[ERROR] /mnt/e/rocketmq_export/rocketmq-exporter-master/src/main/java/org/apache/rocketmq/exporter/service/client/MQAdminExtImpl.java:[561,5] method does not override or implement a method from a supertype
[ERROR] /mnt/e/rocketmq_export/rocketmq-exporter-master/src/main/java/org/apache/rocketmq/exporter/service/client/MQAdminExtImpl.java:[566,5] method does not override or implement a method from a supertype
[INFO] 13 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.152 s
[INFO] Finished at: 2022-06-16T15:54:29+08:00
[INFO] -----------------------------------------------------------------------

**Comment by francisoliverlee** [comment]
the latest version of exporter doest not support 4.5.1.  a little changes can make it ok
