### ISSUE TITLE
not find below metrics that described in document

### ISSUE THREAD

**Issue by MrLYG** [apache/rocketmq-exporter#109]
**Describe the bug**

we get http://xx.xx.xx.xx:5557/metrics inteface, we are not find below metrics,but they are described in document. 
rocketmq_client_consume_fail_msg_count	
rocketmq_client_consume_fail_msg_tps	
rocketmq_client_consume_ok_msg_tps
rocketmq_client_consume_rt	
rocketmq_client_consumer_pull_rt	
rocketmq_client_consumer_pull_tps

**Comment by francisoliverlee** [comment]
exporter changed a lot. The latest version shall be OK
