### ISSUE TITLE
Metric is wrongly written in BrokerRuntimeStats

### ISSUE THREAD

**Issue by MatrixHB** [apache/rocketmq-exporter#111]
`loadTps(this.getTransferedTps, kvTable.getTable().get("getTransferedTps"));`

The "getTransferedTps" is wrongly written, which should be "getTransferredTps" instead. This bug will cause NullPointerException when collecting metrics.

![image](https://user-images.githubusercontent.com/23614576/190095852-1ebb80f1-03e6-46cf-bd0d-4556fd15f712.png)

**Comment by 0daypwn** [comment]
目前使用的RocketMQ版本是 4.9.2，里面变量名是 getTransferedTps
这里是否应该对之前错误的 typo 进行兼容？
