### ISSUE TITLE
Build Binary have error

### ISSUE THREAD

**Issue by zhengbucuo** [apache/rocketmq-exporter#115]
branch master;

after mvn clean install , run jar java -jar target/rocketmq-exporter-0.0.2-SNAPSHOT.jar, have error.
![image](https://user-images.githubusercontent.com/31462232/196028839-cfae427f-43f2-4dd8-9faf-5cec06da2412.png)
```bash
root@infra-promtheus1:/opt/rocketmq-prod/rocketmq-exporter# git branch 
* master
root@infra-promtheus1:/opt/rocketmq-prod/rocketmq-exporter# java -jar target/rocketmq-exporter-0.0.2-SNAPSHOT.jar
no main manifest attribute, in target/rocketmq-exporter-0.0.2-SNAPSHOT.jar
```

**Comment by Narlim** [comment]
just use rocketmq-exporter-0.0.2-SNAPSHOT-exec.jar

**Comment by taizilongxu** [comment]
emmm, why not fix the readme?

**Comment by chinaboy007** [comment]
java -jar target/rocketmq-exporter-0.0.2-SNAPSHOT.jar
no main manifest attribute, in target/rocketmq-exporter-0.0.2-SNAPSHOT.jar
