### ISSUE TITLE
like rocketmq_broker_tps, rocketmq_broker_qps metrics defined wrong

### ISSUE THREAD

**Issue by herbxu** [apache/rocketmq-exporter#123]
**Describe the bug**
As we all know, Prometheus pulled metrics from rocketmq exporter. Because rocketmq_broker_tps, rocketmq_broker_qps used Gauge Metric Type, only can be collected by Prometheus at last metric value pull time. this last metric value only represented last value, will loss many information between each Prometheus pull time. In conclusion, these metric type like QPS, RT should use Counter Metric Type, then use PromSQL calculate QPS or RT like this http metrics defined:
QPS: sum(rate(http_server_requests_total{method="GET"}[$__interval]])) by (method)
RT: sum(increase(http_server_requests_latency_ms_total{method="GET"}[$__interval])) by (method) / (sum(increase(http_server_requests_total{method="GET"}[$__interval])) by (method) > 0)

**Comment by chuqiao8250** [comment]
rocketmq_broker_tps  metrics指标怎么没有了？是有其它metrics 替代了吗？

**Comment by chinaboy007** [comment]
> rocketmq_broker_tps metrics指标怎么没有了？是有其它metrics 替代了吗？

 me too, why not rocketmq_broker_tps metric and rocketmq_broker_qps metric ?
