### ISSUE TITLE
org.apache.rocketmq.exporter.model.BrokerRuntimeStats构造器中拼写错误[getTransferedTps] ，错误拼写为[getTransferredTps]，多了个[r].

### ISSUE THREAD

**Issue by zhangxb1987** [apache/rocketmq-exporter#124]
**Describe the bug**
org.apache.rocketmq.exporter.model.BrokerRuntimeStats构造器中拼写错误[getTransferedTps] ，错误拼写为[getTransferredTps]，多了个[r].

**To Reproduce**
1. Go to 'org.apache.rocketmq.exporter.model.BrokerRuntimeStats.java'
2. loadTps(this.getTransferedTps, kvTable.getTable().get("getTransferredTps"));

**Expected behavior**
getTransferedTps

**Screenshots**

**Comment by maixiaohai** [comment]
the spelling is ok
