### ISSUE TITLE
How to configure acl authentication

### ISSUE THREAD

**Issue by big-loser** [apache/rocketmq-exporter#14]
My rocket has plain_acl authentication. 

What parameters are used to configure authentication?

thanks

**Comment by francisoliverlee** [comment]
@big-loser what's rocketmq version for ?

**Comment by big-loser** [comment]
> @big-loser what's rocketmq version for ?

4.6.0

**Comment by francisoliverlee** [comment]
no need ACL config for metrics collecting.
