### ISSUE TITLE
Could the community publish the official images of Rocketmq-Exporter?

### ISSUE THREAD

**Issue by peachisai** [apache/rocketmq-exporter#153]
The RocketMQ official website has introduced the Prometheus exporter, I have been using it for monitoring RocketMQ.
But there are no official Docker images If the official images could be published, I would greatly appreciate it.

**Comment by caigy** [comment]
@peachisai `rocketmq-exporter` has not been released with docker images, I'd like to add one if it is necessary. Are there any specific requirements for this docker image?

**Comment by peachisai** [comment]
> @peachisai `rocketmq-exporter` has not been released with docker images, I'd like to add one if it is necessary. Are there any specific requirements for this docker image?

Thank you for the promotion.I think the latest code version is good, no other specific requirements.

**Comment by caigy** [comment]
I'll apply for a docker repo for rocketmq-exporter under Apache organization.

**Comment by caigy** [comment]
duplicated #151

**Comment by peachisai** [comment]
@caigy Hello,I have seen the official docker images on the hub,Thank you for your work!

**Comment by peachisai** [comment]
> duplicated #151

Thank you for your hard work,I have seen the  ```0.0.2-snapshot``` version had released on
the docker hub, I want to know when will the official version will be released,Thank you again.
