### ISSUE TITLE
不支持5.1版本吧

### ISSUE THREAD

**Issue by iamqq23ue** [apache/rocketmq-exporter#164]
试了5.1.3版本，使用exporter，几乎没有什么指标了

**Comment by caigy** [comment]
Pls provide more information about this issue, such as the version of rocketmq-exporter, error messages in logs, etc.

**Comment by iamqq23ue** [comment]
> Pls provide more information about this issue, such as the version of rocketmq-exporter, error messages in logs, etc.

rocketmq-exporter-0.0.2,I thought there was always only one version.Just found out that a new RC version has appeared.

**Comment by caigy** [comment]
@iamqq23ue Any error messages in the log of rocketmq-exporter?

**Comment by iamqq23ue** [comment]
谢谢，三月我们试用一下新版本exporter再反馈



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月23日(周五) 晚上7:22
收件人: ***@***.***&gt;;
抄送: "Ryan ***@***.******@***.***&gt;;
主题: Re: [apache/rocketmq-exporter] 不支持5.1版本吧 (Issue #164)




 
@iamqq23ue Any error messages in the log of rocketmq-exporter?

**Comment by iamqq23ue** [comment]
@caigy 您好。随便启动一个rocketmq5的集群，然后用exporter获取数据，都基本没有数据。我理解不用任何条件就能复现。

**Comment by caigy** [comment]
rocketmq 5.2.0 + rocketmq-exporter 0.0.2: 无法复现
![image](https://github.com/apache/rocketmq-exporter/assets/17410645/7201213d-7d5a-49b4-b8ec-78a3ae3ffff6)

**Comment by iamqq23ue** [comment]
@caigy ，谢谢，试了5.2.0，确实指标多了。不过好像还是少了一些，比如写入时间1ms,10ms数量这种指标

**Comment by Kammingyeung** [comment]
@iamqq23ue 你编译没有报错吗

**Comment by Kammingyeung** [comment]
为什么我报错
![image](https://github.com/apache/rocketmq-exporter/assets/167512711/9ab1edae-7d67-46e4-8fc8-735eb3a19f93)

**Comment by Kammingyeung** [comment]
> > @iamqq23ue 你编译没有报错吗
> 
> 编译最新的代码，需要的指标都有了。版本号还是0.0.2但是代码改了。编译报错跳过测试即可，我降了surfire的版本

我上面的报错应该如何解决，就是直接用mvn clean install编译的最新代码

**Comment by iamqq23ue** [comment]
> > > @iamqq23ue 你编译没有报错吗
> > 
> > 
> > 编译最新的代码，需要的指标都有了。版本号还是0.0.2但是代码改了。编译报错跳过测试即可，我降了surfire的版本
> 
> 我上面的报错应该如何解决，就是直接用mvn clean install编译的最新代码

你这个我没遇到，是不是你不小心动了哪的格式啊。我只遇到了依赖包下不下来，改了版本解决了，五月份下载的代码编译的。
