### ISSUE TITLE
it can not find monitoring item

### ISSUE THREAD

**Issue by stevenzyk** [apache/rocketmq-exporter#17]
hi,
After build package with master branch and started up exporter, i can not find some monitoring item. 
like rocketmq_broker_tps / rocketmq_broker_tps / rocketmq_producer_tps and so on.
from latest code, i also can not find these monitoring item. 
Is there anything wrong from my side ?

**Comment by francisoliverlee** [comment]
@stevenzyk  
metrics names changed , you can use these below:
rocketmq_broker_get_nums
rocketmq_broker_put_nums
rocketmq_brokeruntime_commitlog_disk_ratio
rocketmq_brokeruntime_commitlog_maxoffset
rocketmq_brokeruntime_commitlog_minoffset
rocketmq_brokeruntime_commitlogdir_capacity_free
rocketmq_brokeruntime_commitlogdir_capacity_total
rocketmq_brokeruntime_consumequeue_disk_ratio
rocketmq_brokeruntime_dispatch_behind_bytes
rocketmq_brokeruntime_dispatch_maxbuffer
rocketmq_brokeruntime_earliest_message_timestamp
rocketmq_brokeruntime_getfound_tps10
rocketmq_brokeruntime_getfound_tps60
rocketmq_brokeruntime_getfound_tps600
rocketmq_brokeruntime_getmessage_entire_time_max
rocketmq_brokeruntime_getmiss_tps10
rocketmq_brokeruntime_getmiss_tps60
rocketmq_brokeruntime_getmiss_tps600
rocketmq_brokeruntime_gettotal_tps10
rocketmq_brokeruntime_gettotal_tps60
rocketmq_brokeruntime_gettotal_tps600
rocketmq_brokeruntime_gettransfered_tps10
rocketmq_brokeruntime_gettransfered_tps60
rocketmq_brokeruntime_gettransfered_tps600
rocketmq_brokeruntime_msg_gettotal_today_now
rocketmq_brokeruntime_msg_gettotal_todaymorning
rocketmq_brokeruntime_msg_gettotal_yesterdaymorning
rocketmq_brokeruntime_msg_put_total_today_now
rocketmq_brokeruntime_msg_puttotal_todaymorning
rocketmq_brokeruntime_msg_puttotal_yesterdaymorning
rocketmq_brokeruntime_pagecache_lock_time_mills
rocketmq_brokeruntime_pmdt_0ms
rocketmq_brokeruntime_pmdt_0to10ms
rocketmq_brokeruntime_pmdt_100to200ms
rocketmq_brokeruntime_pmdt_10stomore
rocketmq_brokeruntime_pmdt_10to50ms
rocketmq_brokeruntime_pmdt_1to2s
rocketmq_brokeruntime_pmdt_200to500ms
rocketmq_brokeruntime_pmdt_2to3s
rocketmq_brokeruntime_pmdt_3to4s
rocketmq_brokeruntime_pmdt_4to5s
rocketmq_brokeruntime_pmdt_500to1s
rocketmq_brokeruntime_pmdt_50to100ms
rocketmq_brokeruntime_pmdt_5to10s
rocketmq_brokeruntime_pull_threadpoolqueue_capacity
rocketmq_brokeruntime_pull_threadpoolqueue_headwait_timemills
rocketmq_brokeruntime_pull_threadpoolqueue_size
rocketmq_brokeruntime_put_message_average_size
rocketmq_brokeruntime_put_message_size_total
rocketmq_brokeruntime_put_tps10
rocketmq_brokeruntime_put_tps60
rocketmq_brokeruntime_put_tps600
rocketmq_brokeruntime_putmessage_entire_time_max
rocketmq_brokeruntime_putmessage_times_total
rocketmq_brokeruntime_query_threadpool_queue_capacity
rocketmq_brokeruntime_query_threadpoolqueue_headwait_timemills
rocketmq_brokeruntime_query_threadpoolqueue_size
rocketmq_brokeruntime_remain_howmanydata_toflush
rocketmq_brokeruntime_remain_transientstore_buffer_numbs
rocketmq_brokeruntime_send_threadpool_queue_size
rocketmq_brokeruntime_send_threadpoolqueue_capacity
rocketmq_brokeruntime_send_threadpoolqueue_headwait_timemills
rocketmq_brokeruntime_start_accept_sendrequest_time
rocketmq_client_consume_fail_msg_count
rocketmq_client_consume_fail_msg_tps
rocketmq_client_consume_ok_msg_tps
rocketmq_client_consume_rt
rocketmq_client_consumer_pull_rt
rocketmq_client_consumer_pull_tps
rocketmq_group_broker_total_offset
rocketmq_group_consume_total_offset
rocketmq_group_consume_tps
rocketmq_group_count
rocketmq_group_diff
rocketmq_group_get_messagesize
rocketmq_group_get_nums
rocketmq_group_retrydiff
rocketmq_send_back_nums
rocketmq_topic_dlq_offset
rocketmq_topic_offset
rocketmq_topic_put_messagesize
rocketmq_topic_put_nums
rocketmq_topic_retry_offset

**Comment by stevenzyk** [comment]
Thanks a lot!

BR
Steven.zhu (朱轶坤)


francis lee <notifications@github.com> 于2020年4月10日周五 下午6:41写道：
