### ISSUE TITLE
can not find producer-related metrics from metrics api

### ISSUE THREAD

**Issue by SjhZju** [apache/rocketmq-exporter#20]
hi,
    I clone rocketMq exporter and build binary as Readme said. But I can not find producer-related metrics when i running jar file. 

    commit revision： 5d25982183c283e62ca63d6cd859dfaa74363b29
    rocketMq version:  V4_7_0 and V4_6_0
    command:  java -Drocketmq.config.namesrvAddr="{{host}}:{{port}}" -Drocketmq.config.rocketmqVersion="V4_7_0" -jar /path/to/rocketmq-exporter-0.0.2-SNAPSHOT.jar

  I call from browser and try to search 'producer' but got nothing.
  Thanks

**Comment by francisoliverlee** [comment]
@SjhZju 
you can calc those producer-related metrics from some metrics.
rocketmq_topic_put_nums TO producer tps
rocketmq_topic_put_messagesize TO producer message size

**Comment by SjhZju** [comment]
@francisoliverlee 
thanks, I will try these metrics
