### ISSUE TITLE
please update grafana dashboard json

### ISSUE THREAD

**Issue by wolftankk** [apache/rocketmq-exporter#22]
**Describe the bug**
In the last commit, some metric names has changed, E.X: 
rocketmq_consumer_tps  => rocketmq_client_consumer_pull_tps

**Comment by hdchen** [comment]
We recently made an update and reorganized the metrics names in the code, and now it should be able to match dashboard json。

**Comment by alvinwangs** [comment]
Can not found the producer metrics
![image](https://user-images.githubusercontent.com/43318274/82804216-79069d80-9eb4-11ea-988c-59e338fc6ff2.png)

**Comment by hdchen** [comment]
Update to the latest code, and then try

**Comment by vongosling** [comment]
@hdchen Do we have any plan for the first release for production ready?

**Comment by wolftankk** [comment]
I have updated to the latest code, some metric not changed.
