### ISSUE TITLE
Building Failed.

### ISSUE THREAD

**Issue by wkshare** [apache/rocketmq-exporter#23]
**Describe the bug**
Building Failed

**Additional context**
`[INFO] Starting audit...
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/config/CollectClientMetricExecutorConfig.java:1: error: Line does not match expected header line of '/\*'.
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/config/ScheduleConfig.java:1: error: Line does not match expected header line of '/\*'.
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/collector/RMQMetricsCollector.java:69: error: 'member def modifier' have incorrect indentation level 5, expected level should be 4.
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/collector/RMQMetricsCollector.java:71: error: 'member def modifier' have incorrect indentation level 5, expected level should be 4.
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/collector/RMQMetricsCollector.java:73: error: 'member def modifier' have incorrect indentation level 5, expected level should be 4.
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/collector/RMQMetricsCollector.java:75: error: 'member def modifier' have incorrect indentation level 5, expected level should be 4.
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/collector/RMQMetricsCollector.java:77: error: 'member def modifier' have incorrect indentation level 5, expected level should be 4.
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/collector/RMQMetricsCollector.java:79: error: 'member def modifier' have incorrect indentation level 5, expected level should be 4.
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/collector/RMQMetricsCollector.java:171:33: error: Name 'GROUP_DIFF_LABEL_NAMES' must match pattern '^[a-z][a-zA-Z0-9]*$'.
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/collector/RMQMetricsCollector.java:184:33: error: Name 'GROUP_COUNT_LABEL_NAMES' must match pattern '^[a-z][a-zA-Z0-9]*$'.
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/collector/RMQMetricsCollector.java:220:33: error: Name 'TOPIC_OFFSET_LABEL_NAMES' must match pattern '^[a-z][a-zA-Z0-9]*$'.
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/collector/RMQMetricsCollector.java:224:33: error: Name 'DLQ_TOPIC_OFFSET_LABEL_NAMES' must match pattern '^[a-z][a-zA-Z0-9]*$'.
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/collector/RMQMetricsCollector.java:289:33: error: Name 'GROUP_CLIENT_METRIC_LABEL_NAMES' must match pattern '^[a-z][a-zA-Z0-9]*$'.
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/collector/RMQMetricsCollector.java:341:33: error: Name 'GROUP_PULL_LATENCY_LABEL_NAMES' must match pattern '^[a-z][a-zA-Z0-9]*$'.
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/collector/RMQMetricsCollector.java:344:33: error: Name 'GROUP_LATENCY_BY_STORETIME_LABEL_NAMES' must match pattern '^[a-z][a-zA-Z0-9]*$'.
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/collector/RMQMetricsCollector.java:348:33: error: Name 'BROKER_NUMS_LABEL_NAMES' must match pattern '^[a-z][a-zA-Z0-9]*$'.
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/collector/RMQMetricsCollector.java:374:33: error: Name 'GROUP_NUMS_LABEL_NAMES' must match pattern '^[a-z][a-zA-Z0-9]*$'.
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/collector/RMQMetricsCollector.java:518:33: error: Name 'TOPIC_NUMS_LABEL_NAMES' must match pattern '^[a-z][a-zA-Z0-9]*$'.
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/collector/RMQMetricsCollector.java:1002:33: error: Name 'BROKER_RUNTIME_METRIC_LABEL_NAMES' must match pattern '^[a-z][a-zA-Z0-9]*$'.
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/model/common/TwoTuple.java:1: error: Line does not match expected header line of '/\*'.
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/model/metrics/DLQTopicOffsetMetric.java:1: error: Line does not match expected header line of '/\*'.
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/model/metrics/brokerruntime/BrokerRuntimeMetric.java:1: error: Line does not match expected header line of '/\*'.
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/model/metrics/clientrunime/ConsumerRuntimeConsumeFailedTPSMetric.java:1: error: Line does not match expected header line of '/\*'.
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/model/metrics/clientrunime/ConsumerRuntimePullTPSMetric.java:1: error: Line does not match expected header line of '/\*'.
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/model/metrics/clientrunime/ConsumerRuntimeConsumeFailedMsgsMetric.java:1: error: Line does not match expected header line of '/\*'.
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/model/metrics/clientrunime/ConsumerRuntimeConsumeRTMetric.java:1: error: Line does not match expected header line of '/\*'.
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/model/metrics/clientrunime/ConsumerRuntimePullRTMetric.java:1: error: Line does not match expected header line of '/\*'.
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/model/metrics/clientrunime/ConsumerRuntimeConsumeOKTPSMetric.java:1: error: Line does not match expected header line of '/\*'.
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/model/metrics/ConsumerTopicDiffMetric.java:1: error: Line does not match expected header line of '/\*'.
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/model/metrics/ConsumerTopicDiffMetric.java:14: error: Not allow chinese character !
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/model/metrics/ConsumerCountMetric.java:1: error: Line does not match expected header line of '/\*'.
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/model/metrics/ProducerMetric.java:19: error: Not allow chinese character !
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/model/metrics/TopicPutNumMetric.java:1: error: Line does not match expected header line of '/\*'.
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/model/BrokerRuntimeStats.java:1: error: Line does not match expected header line of '/\*'.
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/task/ClientMetricTaskRunnable.java:1: error: Line does not match expected header line of '/\*'.
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/task/ClientMetricCollectorFixedThreadPoolExecutor.java:1: error: Line does not match expected header line of '/\*'.
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/task/MetricsCollectTask.java:122: error: Not allow chinese character !
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/task/MetricsCollectTask.java:569: error: Not allow chinese character !
/root/rocketmq-exporter/src/main/java/org/apache/rocketmq/exporter/task/MetricsCollectTask.java:570: error: Not allow chinese character !
Audit done.`

**Comment by hdchen** [comment]
We have fixed this problem, please re-pull the latest code to try！
