### ISSUE TITLE
The stats <TOPIC_PUT_NUMS> <mytopic> not exist

### ISSUE THREAD

**Issue by helloworlde** [apache/rocketmq-exporter#24]
**Describe the bug**

```
TOPIC_PUT_NUMS-error, topic=mytopic, master broker=1.2.3.4:10911, The stats <TOPIC_PUT_NUMS> <mytopic> not exist
```

**Additional context**
Almost every topic fetch metrics failed, and topic has traffic. My rocketmq version is 4_5_1, did I missed configuration?

**Comment by francisoliverlee** [comment]
@helloworlde 
no sending any message, no TOPIC_PUT_NUMS and TOPIC_PUT_SIZE.
not lastest exporter code, no TOPIC_PUT_NUMS and TOPIC_PUT_SIZE.

**Comment by helloworlde** [comment]
> @helloworlde
> no sending any message, no TOPIC_PUT_NUMS and TOPIC_PUT_SIZE.
> not lastest exporter code, no TOPIC_PUT_NUMS and TOPIC_PUT_SIZE.

Some topic has send message yet, but it still has error, if there need offset different to fetch data?

**Comment by francisoliverlee** [comment]
@helloworlde 4.5.1 has supported ACL, now exporter not. 
do u have interest in make a PR to upgrade the exporter to support ACL. if it's passed tests, i can merge you PR

**Comment by francisoliverlee** [comment]
@helloworlde 
we add acl to the exporter, can you check that in your clusters. RocketMQ version should be >= 4.4.0
https://github.com/francisoliverlee/rocketmq-exporter/tree/add-ACL

**Comment by maixiaohai** [comment]
> @helloworlde
> we add acl to the exporter, can you check that in your clusters. RocketMQ version should be >= 4.4.0
> https://github.com/francisoliverlee/rocketmq-exporter/tree/add-ACL

@francisoliverlee Our cluster used aclEnable=true config, and found exporter can't get most metrics data.
I've backport your pr and it worked well.
