### ISSUE TITLE
NO Support Apache RocketMQ version 4.7.1 ; build error

### ISSUE THREAD

**Issue by yyt701** [apache/rocketmq-exporter#34]
@Service("mqAdminExtImpl")
public class MQAdminExtImpl implements MQAdminExt {
    @Autowired

.....

Multiple markers at this line
	- The type MQAdminExtImpl must implement the inherited abstract method MQAdminExt.deletePlainAccessConfig(String, String)
	- The type MQAdminExtImpl must implement the inherited abstract method MQAdminExt.examineBrokerClusterAclVersionInfo(String)
	- The type MQAdminExtImpl must implement the inherited abstract method MQAdminExt.examineBrokerClusterAclConfig(String)
	- The type MQAdminExtImpl must implement the inherited abstract method MQAdminExt.createAndUpdatePlainAccessConfig(String, 
	 PlainAccessConfig)
	- The type MQAdminExtImpl must implement the inherited abstract method MQAdminExt.resumeCheckHalfMessage(String)
	- The type MQAdminExtImpl must implement the inherited abstract method MQAdminExt.resumeCheckHalfMessage(String, String)
	- The type MQAdminExtImpl must implement the inherited abstract method MQAdminExt.updateGlobalWhiteAddrConfig(String, String)

=======

DefaultMQPullConsumer pullConsumer = new DefaultMQPullConsumer(TOOLS_CONSUMER_GROUP, null);

Multiple markers at this line
	- The type DefaultMQPullConsumer is deprecated
	- The type DefaultMQPullConsumer is deprecated
	- The constructor DefaultMQPullConsumer(String, RPCHook) is 
	 ambiguous

**Comment by francisoliverlee** [comment]
@yyt701 try the lastest code
