### ISSUE TITLE
A required class was missing while executing org.springframework.boot:spring-boot-maven-plugin:2.1.2.RELEASE:repackage: org/apache/maven/shared/utils/StringUtils

### ISSUE THREAD

**Issue by iamqq23ue** [apache/rocketmq-exporter#40]
When i execute mvn clean install，an error is reported during compilation,the log is as follows。
Modify pom.xml to
  <plugin>
                 <groupId>org.springframework.boot</groupId>
                 <artifactId>spring-boot-maven-plugin</artifactId>
             </plugin>

change into
  <plugin>
                 <groupId>org.springframework.boot</groupId>
                 <artifactId>spring-boot-maven-plugin</artifactId>
                <version>1.5.7.RELEASE</version>
             </plugin>

No more errors. But the setting in parent is also 2.1.2, I want to know why?
<parent>
         <groupId>org.springframework.boot</groupId>
         <artifactId>spring-boot-starter-parent</artifactId>
         <version>2.1.2.RELEASE</version>
         <relativePath/> 
     </parent>

error log：

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.231 s
[INFO] Finished at: 2020-11-06T15:54:59+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.1.2.RELEASE:repackage (repackage) on project rocketmq-exporter: Execution repackage of goal org.springframework.boot:spring-boot-maven-plugin:2.1.2.RELEASE:repackage failed: A required class was missing while executing org.springframework.boot:spring-boot-maven-plugin:2.1.2.RELEASE:repackage: org/apache/maven/shared/utils/StringUtils
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.springframework.boot:spring-boot-maven-plugin:2.1.2.RELEASE

**Comment by francisoliverlee** [comment]
it seems something with the maven or java not right.  mine is build success and env as bellow:
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/liwei/data/apps/maven
Java version: 1.8.0_191, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"
```

**Comment by francisoliverlee** [comment]
i will close the issue, any problems, feel free to reopen it
