### ISSUE TITLE
can't build image, get no such file or directory error

### ISSUE THREAD

**Issue by ffff121** [apache/rocketmq-exporter#48]
**Describe the bug**

**To Reproduce**
1. clone master branch
2. exec “mvn package -Dmaven.test.skip=true docker:build”
3. get error “ADD failed: stat /mnt/sda1/var/lib/docker/tmp/docker-builder484560312/rocketmq-exporter-0.0.1-SNAPSHOT.jar: no such file or directory ”
`
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.604 s
[INFO] Finished at: 2020-12-30T12:18:41+08:00
[INFO] Final Memory: 35M/124M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.11:build (default-cli) on project rocketmq-exporter: Exception caught: ADD failed: stat /mnt/sda1/var/lib/docker/tmp/docker-builder484560312/rocketmq-exporter-0.0.1-SNAPSHOT.jar: no such file or directory -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
`

OS: window10
maven: 3.6.3
jdk: 11
docker: 18.03.0-ce, build 0520e24302

need help，plz

**Comment by vongosling** [comment]
Could not support JDK 11+ now :-(

**Comment by ffff121** [comment]
> You could try again using the latest code. BTW, the project is not well-tested using JDK 11+ now, you are welcome to make pr when running into any related issues.

thx. i will.
