### ISSUE TITLE
RocketMQ deleted the topic and subscription group, but prometheus still has related alarm information

### ISSUE THREAD

**Issue by lanyuange** [apache/rocketmq-exporter#62]
![image](https://user-images.githubusercontent.com/19629949/127422412-200b9bf6-4bdd-468e-94d0-8c900a52eb36.png)
![image](https://user-images.githubusercontent.com/19629949/127422424-0b12bc4e-c1df-436f-bf1e-309946877913.png)
![image](https://user-images.githubusercontent.com/19629949/127422437-8418e534-8f10-471d-8a5b-a3cdb28703f2.png)

**Comment by francisoliverlee** [comment]
for xxxx_diff,  you could take countOfOnlineConsumers into consideratio

**Comment by lanyuange** [comment]
How to set？

**Comment by hdchen** [comment]
参考#78
