### ISSUE TITLE
failed to convert java.lang.String to long

### ISSUE THREAD

**Issue by ZhaoUncle** [apache/rocketmq-exporter#69]
I don't update application.yml ,the service start failed.
![image](https://user-images.githubusercontent.com/31182637/134636983-8252400e-5344-423c-b803-fc744ad4b15e.png)

**Comment by maixiaohai** [comment]
@humkum Can you help to fix it?

**Comment by humkum** [comment]
> @humkum Can you help to fix it?

ok~

**Comment by maixiaohai** [comment]
@ZhaoUncle can you help to check if the pr can fix your problem

**Comment by ZhaoUncle** [comment]
#71  it fix this problem,I check. @maixiaohai
