### ISSUE TITLE
Metrics rocketmq_consumer_offset's tag countOfOnlineConsumers doesn't behave as expected

### ISSUE THREAD

**Issue by RichardChengshaojin** [apache/rocketmq-exporter#78]
**Describe the bug**
I deleted the subscription group, then queried the metrics **rocketmq_consumer_offset** in prometheus, and found the value of tag **countOfOnlineConsumers** was still 1.

**To Reproduce**
1. Delete the subscription group through rocketmq console or the script provided by rocket mq `sh mqadmin deleteSubGroup -n namesrv -c cluster -g groupName`, say groupName is **test-accumulate-consumer-1**
2. Query metrics through prometheus, `rocketmq_group_diff{group="test-accumulate-consumer-1"}`
3. Result is 
![图片](https://user-images.githubusercontent.com/10008660/144375758-5c6c1850-dbce-40fa-b79e-00882bed04d6.png)
4. As shown in console, find no consumer
5. 
![图片](https://user-images.githubusercontent.com/10008660/144375915-38551f3a-e3ed-4cb0-9b61-72ddd0984160.png)

**Expected behavior** 
Expect the value of tag `countOfOnlineConsumers`  to be `0` rather than `1`. As shown below
`rocketmq_group_diff{countOfOnlineConsumers="0",group="test-accumulate-consumer-1",instance="172.20.22.30:5557",job="dev-metrics",msgModel="1",topic="test-accumulate"}`

**Desktop (please complete the following information):**
 - Rocketmq broker version is V4_7_0

**Additional context**
I found a similar issue here: https://github.com/apache/rocketmq-exporter/issues/62

**Comment by hdchen** [comment]
eg After deleting this consumer group test-accumulate-consumer-1, this metric rocketmq_group_diff{group="test-accumulate-consumer-1"}  will be deleted in  prometheus after default  1 minutes , related to this  outOfTimeSeconds   parameter in application.yml
