### ISSUE TITLE
The metric of rocketmq_group_diff show the error result for boardcast consumer

### ISSUE THREAD

**Issue by qsrg** [apache/rocketmq-exporter#79]
if consume model is boardcast, rocketmq_group_diff  should not show the error result.

in rocketmq-console：
![微信图片编辑_20211222193812](https://user-images.githubusercontent.com/42698388/147087212-74d9b92f-d86e-48d4-850f-e2e1f27dbbb9.jpg)

in prometheus: data collected by exporter 
![Image1](https://user-images.githubusercontent.com/42698388/147096967-4faef57e-6ddf-4474-9b3d-f6b2f9e06e61.png)

**Comment by maixiaohai** [comment]
merged
