### ISSUE TITLE
How to monitor jvm?

### ISSUE THREAD

**Issue by superfenv** [apache/rocketmq-exporter#8]
Just like monitoring kafka, open the jmx port and obtain monitoring indicators through jvm_exporter.

**Comment by francisoliverlee** [comment]
jvm is the basic metrics. rmq exporter should not be used for this. try: cat, telegraf

**Comment by superfenv** [comment]
I am very happy to receive your letter and wish you all the best.
Rocketmq-exporter has fewer monitoring indicators and needs to monitor more
indicators. Telegraf cannot write data directly to prometheus, what should
I do?

francis lee <notifications@github.com> 于2019年12月16日周一 下午8:23写道：

**Comment by francisoliverlee** [comment]
@superfenv prometheus has a [push gateway](https://github.com/prometheus/pushgateway), you can write a tool to push metric to promethues
