### ISSUE TITLE
no have  rocketmq_message_accumulation and rocketmq_group_get_latency 

### ISSUE THREAD

**Issue by qifeng998130** [apache/rocketmq-exporter#81]
**Describe the bug**
How to get rocketmq_message_accumulation and rocketmq_group_get_latency 

**To Reproduce**
 I checked the source code by [RMQMetricsCollect.java]https://github.com/apache/rocketmq-exporter/blob/master/src/main/java/org/apache/rocketmq/exporter/collector/RMQMetricsCollector.java. But I didn't find it，
How to get rocketmq_message_accumulation and rocketmq_group_get_latency 

@jimjag @jimjag @WillemJiang @ke4qqq @jimjag @jimjag @jimjag

**Comment by maixiaohai** [comment]
@qifeng998130 metric `rocketmq_message_accumulation` may replaced by `rocketmq_group_diff`, can you help update the README?

**Comment by qifeng998130** [comment]
> @qifeng998130 metric`rocketmq_message_accumulation`可能被替换为`rocketmq_group_diff`，你能帮忙更新 README 吗？

where is rocketmq_group_get_latency

**Comment by qifeng998130** [comment]
> @qifeng998130 metric `rocketmq_message_accumulation` may replaced by `rocketmq_group_diff`, can you help update the README?
I sure.
no have rocketmq_group_get_latency ？
How to get rocketmq_group_get_latency
