### ISSUE TITLE
no have rocketmq_group_get_latency #81

### ISSUE THREAD

**Issue by qifeng998130** [apache/rocketmq-exporter#82]
**Describe the bug** 
What has metric  rocketmq_group_get_latency  replaced ？
**To Reproduce** 
I checked the source code by [RMQMetricsCollect.java]https://github.com/apache/rocketmq-exporter/blob/master/src/main/java/org/apache/rocketmq/exporter/collector/RMQMetricsCollector.java. But I didn't find it，
How to get rocketmq_group_get_latency？

 @hdchen @duhenglucky

**Comment by hdchen** [comment]
![image](https://user-images.githubusercontent.com/9590928/149621823-0bd29953-a527-4146-8d54-4d81e1adc3d9.png)
